In [ ]:
import os
import camelot
import pandas as pd

def extract_data_from_pdf(pdf_path, pages_to_extract, output_folder, start_index=1):
   
    os.makedirs(output_folder, exist_ok=True)

    extracted_data = {}

    for label, page in pages_to_extract.items():
        print(f"Extracting '{label}' from page {page} of '{pdf_path}'")
        tables = camelot.read_pdf(pdf_path, pages=str(page), flavor='stream')

        if tables:
            extracted_data[label] = [t.df for t in tables]
        else:
            print(f"No tables found on page {page}.")

    for label, dfs in extracted_data.items():
        for idx, df in enumerate(dfs, start=start_index):
            filename = f"{label}_table_{idx}.csv"
            csv_path = os.path.join(output_folder, filename)
            df.to_csv(csv_path, index=False)
            print(f"Saved: {csv_path}")

# Configuration for multiple PDFs
pdf_files = [
    {
        "pdf_path": "2020.pdf",
        "pages_to_extract": {
            "top_20_shareholders": 150,
            "income_statement": 184,
            "net_asset_ebitda": 275,
            "equity_liabilities": 186
        },
        "output_folder": "extracted_csvs/2020",
        "start_index": 2020
    },
    {
        "pdf_path": "2021.pdf",
        "pages_to_extract": {
            "top_20_shareholders": 162,
            "income_statement": 198,
            "net_asset_ebitda": 287,
            "equity_liabilities": 200
        },
        "output_folder": "extracted_csvs/2021",
        "start_index": 2021
    },
    
    {
        "pdf_path": "2022.pdf",
        "pages_to_extract": {
            "top_20_shareholders": 172,
            "income_statement": 208,
            "net_asset_ebitda": 297,
            "equity_liabilities": 210
        },
        "output_folder": "extracted_csvs/2022",
        "start_index": 2022
    },
    {
        "pdf_path": "2023.pdf",
        "pages_to_extract": {
            "top_20_shareholders": 172,
            "income_statement": 216,
            "net_asset_ebitda": 307,
            "equity_liabilities": 218
        },
        "output_folder": "extracted_csvs/2023",
        "start_index": 2023
    },
    {
        "pdf_path": "2024.pdf",
        "pages_to_extract": {
            "top_20_shareholders": 131,
            "income_statement": 276,
            "net_asset_ebitda": 369,
            "equity_liabilities": 278
        },
        "output_folder": "extracted_csvs/2024",
        "start_index": 2024
    }
]

for pdf_file in pdf_files:
    extract_data_from_pdf(
        pdf_path=pdf_file["pdf_path"],
        pages_to_extract=pdf_file["pages_to_extract"],
        output_folder=pdf_file["output_folder"],
        start_index=pdf_file.get("start_index", 1)
    )

In [ ]:
import os
import pandas as pd

def get_all_tables_as_dfs(folder_path):
   
    for file_name in os.listdir(folder_path):
        if file_name.endswith(".csv"):
            
            table_name = file_name.split('.')[0]
           
            table_df = pd.read_csv(os.path.join(folder_path, file_name))
           
            globals()[table_name] = table_df
            print(f"DataFrame for {table_name} is loaded.")

folder_path = "extracted_csvs"  

get_all_tables_as_dfs(folder_path)

DataFrame for equity_liabilities_table_2020 is loaded.
DataFrame for equity_liabilities_table_2021 is loaded.
DataFrame for equity_liabilities_table_2022 is loaded.
DataFrame for equity_liabilities_table_2023 is loaded.
DataFrame for equity_liabilities_table_2024 is loaded.
DataFrame for income_statement_table_2020 is loaded.
DataFrame for income_statement_table_2021 is loaded.
DataFrame for income_statement_table_2022 is loaded.
DataFrame for income_statement_table_2023 is loaded.
DataFrame for income_statement_table_2024 is loaded.
DataFrame for net_asset_ebitda_table_2020 is loaded.
DataFrame for net_asset_ebitda_table_2021 is loaded.
DataFrame for net_asset_ebitda_table_2022 is loaded.
DataFrame for net_asset_ebitda_table_2023 is loaded.
DataFrame for net_asset_ebitda_table_2024 is loaded.
DataFrame for top_20_shareholders_table_2020 is loaded.
DataFrame for top_20_shareholders_table_2021 is loaded.
DataFrame for top_20_shareholders_table_2022 is loaded.
DataFrame for top_20_shareholders_table_2023 is loaded.
DataFrame for top_20_shareholders_table_2024 is loaded.

In [ ]:
import pandas as pd
import re


year_config = {
    "2019": {"income_cols": [3], "other_cols": [2], "tables": {
        "income": income_statement_table_2020,
        "net_asset": net_asset_ebitda_table_2020,
        "equity": equity_liabilities_table_2020,
    }},
    "2020": {"income_cols": [2], "other_cols": [1], "tables": {
        "income": income_statement_table_2020,
        "net_asset": net_asset_ebitda_table_2020,
        "equity": equity_liabilities_table_2020,
    }},
    "2021": {"income_cols": [2], "other_cols": [1], "tables": {
        "income": income_statement_table_2021,
        "net_asset": net_asset_ebitda_table_2021,
        "equity": equity_liabilities_table_2021,
    }},
    "2022": {"income_cols": [2], "other_cols": [1], "tables": {
        "income": income_statement_table_2022,
        "net_asset": net_asset_ebitda_table_2022,
        "equity": equity_liabilities_table_2022,
    }},
    "2023": {"income_cols": [2], "other_cols": [1], "tables": {
        "income": income_statement_table_2023,
        "net_asset": net_asset_ebitda_table_2023,
        "equity": equity_liabilities_table_2023,
    }},
    "2024": {"income_cols": [2], "other_cols": [1], "tables": {
        "income": income_statement_table_2024,
        "net_asset": net_asset_ebitda_table_2024,
        "equity": equity_liabilities_table_2024,
    }},
}


metrics = [
    "Total Revenue", "Cost of Sales", "Gross Profit", "Operating Expenses",
    "Basic EPS", "Diluted EPS", "Net assets per share",  "Total equity and liabilities" ,"Net Profit"
]


extracted = {metric: {} for metric in metrics}


key_mapping = {
    "total revenue": "Total Revenue",
    "cost of sales": "Cost of Sales",
    "gross profit": "Gross Profit",
    "basic": "Basic EPS",
    "diluted": "Diluted EPS",
    "net assets per share": "Net assets per share",
    "total equity and liabilities": "Total equity and liabilities",
    "profit for the year": "Net Profit"
}


expense_keywords = [
    "selling and distribution expenses",
    "administrative expenses",
    "other operating expenses"
]

def clean_value(val):
    val = str(val).replace(",", "").replace("(", "-").replace(")", "")
    return float(val) if val.lower() not in ["nan", "-", ""] else None

def extract_from_df(df, col_indices, year, match_eps_only=False, multiplier=1):
    for _, row in df.iterrows():
        row_text = " ".join(map(str, row)).lower()
        try:
            values = [clean_value(row.iloc[i]) for i in col_indices]
        except:
            values = [None] * len(col_indices)

        matched = False
        for keyword, label in key_mapping.items():
           
            if re.search(rf"\b{re.escape(keyword)}\b", row_text):
                value = values[0]
                if value is not None:
                    extracted[label][year] = value 
                matched = True
                break

        
        if not matched and any(kw in row_text for kw in expense_keywords):
            value = values[0]
            if value is not None:
                extracted["Operating Expenses"][year] = extracted["Operating Expenses"].get(year, 0.0) + value

def extract_specific(df, col_indices, year):
    for _, row in df.iterrows():
        row_text = " ".join(map(str, row)).lower()
        try:
            values = [clean_value(row.iloc[i]) for i in col_indices]
        except:
            values = [None] * len(col_indices)

        if "total equity and liabilities" in row_text:
            value = values[0]
            if value is not None:
                extracted["Total equity and liabilities"][year] = value

for year, config in year_config.items():
    extract_from_df(config["tables"]["income"], config["income_cols"], year, match_eps_only=False)
    extract_from_df(config["tables"]["net_asset"], config["other_cols"], year, match_eps_only=True)
    extract_specific(config["tables"]["equity"], config["income_cols"], year)


result_df = pd.DataFrame(extracted).T
result_df.loc["Basic EPS", "2021"] =  3.62 
result_df.loc["Diluted EPS", "2021"] =  3.62 
result_df.loc["Basic EPS", "2022"] = 15.13
result_df.loc["Diluted EPS", "2022"] = 15.12
result_df.loc["Basic EPS", "2023"] =  13.12 
result_df.loc["Diluted EPS", "2023"] =  13.12 
formatted_df = result_df.copy()

for col in formatted_df.columns:
    formatted_df[col] = formatted_df[col].map(
        lambda x: f"{x:,.2f}" if isinstance(x, (int, float)) and pd.notnull(x) else x
    )

formatted_df
formatted_df.to_json("formatted_financial_data.json", orient="index", indent=4)

In [96]:
formatted_df

,2019,2020,2021,2022,2023,2024
Total Revenue,"135,456,148.00","140,042,560.00","127,675,650.00","218,074,746.00","276,639,907.00","280,772,604.00"
Cost of Sales,"-107,668,833.00","-113,960,929.00","-108,747,058.00","-180,430,008.00","-227,190,277.00","-226,490,684.00"
Gross Profit,"27,787,315.00","26,081,631.00","18,928,592.00","37,644,738.00","49,449,630.00","54,281,920.00"
Operating Expenses,"-22,055,920.00","-21,534,546.00","-19,003,162.00","-32,951,345.00","-40,019,591.00","-43,422,979.00"
Basic EPS,11.13,7.10,3.62,15.13,13.12,8.06
Diluted EPS,156.00,115.40,3.62,15.12,13.12,194.00
Net assets per share,154.90,164.50,171.40,224.80,246.20,238.80
Total equity and liabilities,"363,796,744.00","436,944,019.00","536,794,204.00","717,795,693.00","744,506,415.00","771,191,500.00"
Net Profit,"16,237,396.00","9,740,795.00","3,950,891.00","20,442,907.00","18,896,124.00","12,127,534.00"

In [97]:
top_20_shareholders_table_2020

,0,1,2,3,4
0,NaN,Number of Shares,%,Number of Shares,%
1,Mr S E Captain,"153,211,107",11.62,"152,991,389",11.61
2,Citigroup Global Markets Limited Agency Tradin...,"141,854,717",10.76,-,-
3,Melstacorp PLC,"128,917,111",9.78,"128,572,406",9.75
4,Paints & General Industries Limited,"93,787,615",7.11,"86,673,704",6.58
5,Schroder International Selection Fund,"42,475,806",3.22,"42,417,426",3.22
6,HWIC Asia Fund,"39,250,982",2.98,"36,000,982",2.73
7,Mr R S Captain,"35,733,994",2.71,"26,950,930",2.04
8,Edgbaston Asian Equity Trust,"29,849,703",2.26,"33,018,476",2.50
9,Norges Bank Account 2,"28,394,516",2.15,"21,023,402",1.59
10,Aberdeen Standard Asia Focus PLC,"22,693,572",1.72,"19,793,572",1.50
11,Aberdeen Standard SICAV I - Asia Pacific Equit...,"19,898,613",1.51,"19,898,613",1.51
12,Mr Kandiah Balendra,"19,511,476",1.48,"20,006,476",1.52
13,Fidelity Fund - Pacific,"19,060,108",1.45,"19,060,108",1.45
14,Employees Trust Fund Board,"18,690,918",1.42,"18,834,190",1.43
15,Aberdeen Standard SICAV I - Asian Smaller Comp...,"16,763,554",1.27,"19,600,554",1.49
16,Mrs C S De Fonseka,"13,668,417",1.04,"13,226,598",1.00
17,Schroder Asian Growth Fund,"13,164,018",1.00,"11,282,414",0.86
18,Mrs S A J De Fonseka,"13,122,826",1.00,"13,116,826",1.00
19,LF Ruffer Investment Funds: LF Ruffer Pacific ...,"11,297,899",0.86,"11,297,899",0.86
20,LF Ruffer Total Return Fund,"11,154,285",0.85,"11,154,285",0.85

In [98]:
top_20_shareholders_table_2020

,0,1,2,3,4
0,NaN,Number of Shares,%,Number of Shares,%
1,Mr S E Captain,"153,211,107",11.62,"152,991,389",11.61
2,Citigroup Global Markets Limited Agency Tradin...,"141,854,717",10.76,-,-
3,Melstacorp PLC,"128,917,111",9.78,"128,572,406",9.75
4,Paints & General Industries Limited,"93,787,615",7.11,"86,673,704",6.58
5,Schroder International Selection Fund,"42,475,806",3.22,"42,417,426",3.22
6,HWIC Asia Fund,"39,250,982",2.98,"36,000,982",2.73
7,Mr R S Captain,"35,733,994",2.71,"26,950,930",2.04
8,Edgbaston Asian Equity Trust,"29,849,703",2.26,"33,018,476",2.50
9,Norges Bank Account 2,"28,394,516",2.15,"21,023,402",1.59
10,Aberdeen Standard Asia Focus PLC,"22,693,572",1.72,"19,793,572",1.50
11,Aberdeen Standard SICAV I - Asia Pacific Equit...,"19,898,613",1.51,"19,898,613",1.51
12,Mr Kandiah Balendra,"19,511,476",1.48,"20,006,476",1.52
13,Fidelity Fund - Pacific,"19,060,108",1.45,"19,060,108",1.45
14,Employees Trust Fund Board,"18,690,918",1.42,"18,834,190",1.43
15,Aberdeen Standard SICAV I - Asian Smaller Comp...,"16,763,554",1.27,"19,600,554",1.49
16,Mrs C S De Fonseka,"13,668,417",1.04,"13,226,598",1.00
17,Schroder Asian Growth Fund,"13,164,018",1.00,"11,282,414",0.86
18,Mrs S A J De Fonseka,"13,122,826",1.00,"13,116,826",1.00
19,LF Ruffer Investment Funds: LF Ruffer Pacific ...,"11,297,899",0.86,"11,297,899",0.86
20,LF Ruffer Total Return Fund,"11,154,285",0.85,"11,154,285",0.85

In [99]:
top_20_shareholders_table_2021
top_20_shareholders_table_2021_revised = top_20_shareholders_table_2021.copy()
top_20_shareholders_table_2021_revised

,0,1,2,3,4
0,Top Twenty Shareholders of the Company,NaN,NaN,NaN,NaN
1,NaN,31 Mar 2021,NaN,31 Mar 2020,NaN
2,NaN,Number of,%,Number of,%
3,NaN,Shares,NaN,Shares,NaN
4,Mr S E Captain,"150,769,641",11.42,"153,211,107",11.62
5,Citigroup Global Markets Limited Agency Tradin...,"141,854,717",10.75,"141,854,717",10.76
6,Melstacorp PLC,"128,917,111",9.77,"128,917,111",9.78
7,Paints and General Industries Limited,"114,977,303",8.71,"93,787,615",7.11
8,Schroder International Selection Fund,"42,475,806",3.22,"42,475,806",3.22
9,HWIC Asia Fund,"39,250,982",2.97,"39,250,982",2.98
10,Mr R S Captain,"35,544,282",2.69,"35,733,994",2.71
11,Norges Bank Account 2,"31,706,807",2.40,"28,394,516",2.15
12,Aberdeen Standard Asia Focus PLC,"23,873,572",1.81,"22,693,572",1.72
13,Mr Kandiah Balendra,"19,511,476",1.48,"19,511,476",1.48
14,Employees Trust Fund Board,"18,709,833",1.42,"18,690,918",1.42
15,Fidelity Fund - Pacific,"17,880,904",1.35,"19,060,108",1.45
16,Mrs C S De Fonseka,"16,952,586",1.28,"13,668,417",1.04
17,Mrs S A J De Fonseka,"15,204,230",1.15,"13,122,826",1.00
18,Edgbaston Asian Equity Trust,"14,809,382",1.12,"29,849,703",2.26
19,Chemanex PLC,"11,417,835",0.87,"5,250,569",0.40
20,LF Ruffer Investment Funds: LF Ruffer Pacific ...,"11,297,899",0.86,"11,297,899",0.86
21,Mr K N J Balendra,"10,907,628",0.83,"10,907,628",0.83
22,Schroder Asian Growth Fund,"10,328,047",0.78,"13,164,018",1.00
23,Employee's Provident Fund,"10,159,322",0.77,"10,159,322",0.77

In [100]:
top_20_shareholders_table_2021_final = top_20_shareholders_table_2021_revised.drop(index=[0, 1, 2, 3]).reset_index(drop=True)
top_20_shareholders_table_2021_final

,0,1,2,3,4
0,Mr S E Captain,"150,769,641",11.42,"153,211,107",11.62
1,Citigroup Global Markets Limited Agency Tradin...,"141,854,717",10.75,"141,854,717",10.76
2,Melstacorp PLC,"128,917,111",9.77,"128,917,111",9.78
3,Paints and General Industries Limited,"114,977,303",8.71,"93,787,615",7.11
4,Schroder International Selection Fund,"42,475,806",3.22,"42,475,806",3.22
5,HWIC Asia Fund,"39,250,982",2.97,"39,250,982",2.98
6,Mr R S Captain,"35,544,282",2.69,"35,733,994",2.71
7,Norges Bank Account 2,"31,706,807",2.40,"28,394,516",2.15
8,Aberdeen Standard Asia Focus PLC,"23,873,572",1.81,"22,693,572",1.72
9,Mr Kandiah Balendra,"19,511,476",1.48,"19,511,476",1.48
10,Employees Trust Fund Board,"18,709,833",1.42,"18,690,918",1.42
11,Fidelity Fund - Pacific,"17,880,904",1.35,"19,060,108",1.45
12,Mrs C S De Fonseka,"16,952,586",1.28,"13,668,417",1.04
13,Mrs S A J De Fonseka,"15,204,230",1.15,"13,122,826",1.00
14,Edgbaston Asian Equity Trust,"14,809,382",1.12,"29,849,703",2.26
15,Chemanex PLC,"11,417,835",0.87,"5,250,569",0.40
16,LF Ruffer Investment Funds: LF Ruffer Pacific ...,"11,297,899",0.86,"11,297,899",0.86
17,Mr K N J Balendra,"10,907,628",0.83,"10,907,628",0.83
18,Schroder Asian Growth Fund,"10,328,047",0.78,"13,164,018",1.00
19,Employee's Provident Fund,"10,159,322",0.77,"10,159,322",0.77

In [ ]:

import json
import pandas as pd

# Load JSON data
with open("formatted_financial_data.json") as f:
    raw = json.load(f)


df = pd.DataFrame(raw).T  

df.index.name = "Year"
df.index = df.index.astype(str)

df = df.apply(lambda col: col.map(lambda x: float(str(x).replace(",", ""))))

print("df.index:", df.index.tolist())      
print("df.columns:", df.columns.tolist())  
df.head()

df.index: ['Total Revenue', 'Cost of Sales', 'Gross Profit', 'Operating Expenses', 'Basic EPS', 'Diluted EPS', 'Net assets per share', 'Total equity and liabilities', 'Net Profit']
df.columns: ['2019', '2020', '2021', '2022', '2023', '2024']

,2019,2020,2021,2022,2023,2024
Year,,,,,,
Total Revenue,1.354561e+08,140042560.0,1.276756e+08,2.180747e+08,2.766399e+08,2.807726e+08
Cost of Sales,-1.076688e+08,-113960929.0,-1.087471e+08,-1.804300e+08,-2.271903e+08,-2.264907e+08
Gross Profit,2.778732e+07,26081631.0,1.892859e+07,3.764474e+07,4.944963e+07,5.428192e+07
Operating Expenses,-2.205592e+07,-21534546.0,-1.900316e+07,-3.295134e+07,-4.001959e+07,-4.342298e+07
Basic EPS,1.113000e+01,7.1,3.620000e+00,1.513000e+01,1.312000e+01,8.060000e+00

In [ ]:
def generate_ml_insight(df, selected_year):
    selected_year = str(selected_year)
    
    if selected_year not in df.columns:
        return [f" No financial data available for year {selected_year}"]


    years = list(df.columns)
    year_idx = years.index(selected_year)

    if year_idx == 0:
        return ["ℹ️ Not enough historical data for comparison."]
    
    prev_year = years[year_idx - 1]
    insights = []

    emoji_map = {
        "Total Revenue": "💼",
        "Cost of Sales": "📦",
        "Gross Profit": "📊",
        "Operating Expenses": "🧾",
        "Net Profit": "💰",
        "Basic EPS": "📉",
        "Diluted EPS": "📉",
        "Net assets per share": "🏦",
        "Total equity and liabilities": "🏛️"
    }

    for metric in df.index:
        try:
            current = df.at[metric, selected_year]
            previous = df.at[metric, prev_year]
            change = current - previous
            pct_change = (change / abs(previous)) * 100 if previous != 0 else 0

            tag = emoji_map.get(metric, "📈")

            if pct_change > 10:
                insights.append(f"{tag} {metric} increased by {pct_change:.2f}% in {selected_year} compared to {prev_year}.")
            elif pct_change < -10:
                insights.append(f"{tag} {metric} dropped by {abs(pct_change):.2f}% in {selected_year} compared to {prev_year}.")
            elif abs(pct_change) > 2:
                direction = "rose" if change > 0 else "fell"
                insights.append(f"{tag} {metric} slightly {direction} ({pct_change:.2f}%) in {selected_year} vs {prev_year}.")
        except Exception as e:
            insights.append(f"⚠️ Could not compute insight for {metric}: {str(e)}")

    return insights

In [103]:
insights = generate_ml_insight(df, "2024")
for i, insight in enumerate(insights, 1):
    print(f"{i}. {insight}")

1. 📊 Gross Profit slightly rose (9.77%) in 2024 vs 2023.
2. 🧾 Operating Expenses slightly fell (-8.50%) in 2024 vs 2023.
3. 📉 Basic EPS dropped by 38.57% in 2024 compared to 2023.
4. 📉 Diluted EPS increased by 1378.66% in 2024 compared to 2023.
5. 🏦 Net assets per share slightly fell (-3.01%) in 2024 vs 2023.
6. 🏛️ Total equity and liabilities slightly rose (3.58%) in 2024 vs 2023.
7. 💰 Net Profit dropped by 35.82% in 2024 compared to 2023.

In [124]:
import fitz  
import os

def extract_text_from_pdf(pdf_path, output_txt_path):
    try:
        os.makedirs(os.path.dirname(output_txt_path), exist_ok=True)
        doc = fitz.open(pdf_path)
        full_text = "\n".join([page.get_text() for page in doc])
        with open(output_txt_path, "w", encoding="utf-8") as f:
            f.write(full_text)
        print(f" Saved: {output_txt_path}")
    except Exception as e:
        print(f" Failed for {pdf_path}: {e}")


years = ["2020", "2021", "2022", "2023", "2024"]


for year in years:
    pdf_filename = f"{year}.pdf" 
    output_filename = f"text_output/{year}_report.txt"
    extract_text_from_pdf(pdf_filename, output_filename)

 Saved: text_output/2020_report.txt
 Saved: text_output/2021_report.txt
 Saved: text_output/2022_report.txt
 Saved: text_output/2023_report.txt
 Saved: text_output/2024_report.txt

In [ ]:
import os
import json
import requests

API_KEY = "API_KEY"

def call_openrouter_llm(summary_text):
    prompt = f"""
    From the following annual report excerpt, identify major events or economic disruptions that impacted the company's financial performance. 
    List each event as a bullet point. If no events are mentioned, return an empty list.

    Text: {summary_text}

    Event Annotations:
    """

    url = "https://openrouter.ai/api/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json",
    }

    data = json.dumps({
        "model": "deepseek/deepseek-r1:free",
        "messages": [
            {
                "role": "user",
                "content": prompt.strip()
            }
        ]
    })

    response = requests.post(url, headers=headers, data=data)
    if response.status_code == 200:
        content = response.json()['choices'][0]['message']['content']
        return content.strip().split('\n')
    else:
        print(f"Error {response.status_code}: {response.text}")
        return []

text_folder = "text_output"
years = ["2020", "2021", "2022", "2023", "2024"]
event_annotations = {}

for year in years:
    try:
        with open(f"{text_folder}/{year}_report.txt", "r", encoding="utf-8") as f:
            report_text = f.read()

        print(f"Extracting events for {year}...")
        year_events = call_openrouter_llm(report_text[:3000])  
        event_annotations[year] = [e.strip("•- ") for e in year_events if e.strip()]
    except Exception as e:
        print(f"Failed to process {year}: {e}")
        event_annotations[year] = []


with open("event_annotations.json", "w", encoding="utf-8") as f:
    json.dump(event_annotations, f, indent=2)

print("Saved event_annotations.json")

🔍 Extracting events for 2020...
🔍 Extracting events for 2021...
🔍 Extracting events for 2022...
🔍 Extracting events for 2023...
🔍 Extracting events for 2024...
✅ Saved event_annotations.json

In [106]:
top_20_shareholders_table_2020

,0,1,2,3,4
0,NaN,Number of Shares,%,Number of Shares,%
1,Mr S E Captain,"153,211,107",11.62,"152,991,389",11.61
2,Citigroup Global Markets Limited Agency Tradin...,"141,854,717",10.76,-,-
3,Melstacorp PLC,"128,917,111",9.78,"128,572,406",9.75
4,Paints & General Industries Limited,"93,787,615",7.11,"86,673,704",6.58
5,Schroder International Selection Fund,"42,475,806",3.22,"42,417,426",3.22
6,HWIC Asia Fund,"39,250,982",2.98,"36,000,982",2.73
7,Mr R S Captain,"35,733,994",2.71,"26,950,930",2.04
8,Edgbaston Asian Equity Trust,"29,849,703",2.26,"33,018,476",2.50
9,Norges Bank Account 2,"28,394,516",2.15,"21,023,402",1.59
10,Aberdeen Standard Asia Focus PLC,"22,693,572",1.72,"19,793,572",1.50
11,Aberdeen Standard SICAV I - Asia Pacific Equit...,"19,898,613",1.51,"19,898,613",1.51
12,Mr Kandiah Balendra,"19,511,476",1.48,"20,006,476",1.52
13,Fidelity Fund - Pacific,"19,060,108",1.45,"19,060,108",1.45
14,Employees Trust Fund Board,"18,690,918",1.42,"18,834,190",1.43
15,Aberdeen Standard SICAV I - Asian Smaller Comp...,"16,763,554",1.27,"19,600,554",1.49
16,Mrs C S De Fonseka,"13,668,417",1.04,"13,226,598",1.00
17,Schroder Asian Growth Fund,"13,164,018",1.00,"11,282,414",0.86
18,Mrs S A J De Fonseka,"13,122,826",1.00,"13,116,826",1.00
19,LF Ruffer Investment Funds: LF Ruffer Pacific ...,"11,297,899",0.86,"11,297,899",0.86
20,LF Ruffer Total Return Fund,"11,154,285",0.85,"11,154,285",0.85

In [107]:
top_20_shareholders_table_2021

,0,1,2,3,4
0,Top Twenty Shareholders of the Company,NaN,NaN,NaN,NaN
1,NaN,31 Mar 2021,NaN,31 Mar 2020,NaN
2,NaN,Number of,%,Number of,%
3,NaN,Shares,NaN,Shares,NaN
4,Mr S E Captain,"150,769,641",11.42,"153,211,107",11.62
5,Citigroup Global Markets Limited Agency Tradin...,"141,854,717",10.75,"141,854,717",10.76
6,Melstacorp PLC,"128,917,111",9.77,"128,917,111",9.78
7,Paints and General Industries Limited,"114,977,303",8.71,"93,787,615",7.11
8,Schroder International Selection Fund,"42,475,806",3.22,"42,475,806",3.22
9,HWIC Asia Fund,"39,250,982",2.97,"39,250,982",2.98
10,Mr R S Captain,"35,544,282",2.69,"35,733,994",2.71
11,Norges Bank Account 2,"31,706,807",2.40,"28,394,516",2.15
12,Aberdeen Standard Asia Focus PLC,"23,873,572",1.81,"22,693,572",1.72
13,Mr Kandiah Balendra,"19,511,476",1.48,"19,511,476",1.48
14,Employees Trust Fund Board,"18,709,833",1.42,"18,690,918",1.42
15,Fidelity Fund - Pacific,"17,880,904",1.35,"19,060,108",1.45
16,Mrs C S De Fonseka,"16,952,586",1.28,"13,668,417",1.04
17,Mrs S A J De Fonseka,"15,204,230",1.15,"13,122,826",1.00
18,Edgbaston Asian Equity Trust,"14,809,382",1.12,"29,849,703",2.26
19,Chemanex PLC,"11,417,835",0.87,"5,250,569",0.40
20,LF Ruffer Investment Funds: LF Ruffer Pacific ...,"11,297,899",0.86,"11,297,899",0.86
21,Mr K N J Balendra,"10,907,628",0.83,"10,907,628",0.83
22,Schroder Asian Growth Fund,"10,328,047",0.78,"13,164,018",1.00
23,Employee's Provident Fund,"10,159,322",0.77,"10,159,322",0.77

In [108]:
top_20_shareholders_table_2022

,0,1,2,3,4
0,NaN,31 March 2022,NaN,31 March 2021,NaN
1,NaN,Number of,%,Number of,%
2,NaN,shares,NaN,shares,NaN
3,Paints and General Industries Limited,"140,437,428",10.14,"114,977,303",8.71
4,Mr S E Captain,"134,220,895",9.69,"150,769,641",11.42
5,Melstacorp PLC,"128,917,111",9.31,"128,917,111",9.77
6,HWIC Asia Fund,"119,200,760",8.61,"39,250,982",2.97
7,Asian Development Bank,"65,042,006",4.70,-,-
8,Citigroup Global Markets Limited Agency Tradin...,"61,904,939",4.47,"141,854,717",10.75
9,Schroder International Selection Fund,"41,974,590",3.03,"42,475,806",3.22
10,Mr R S Captain,"34,405,091",2.48,"35,544,282",2.69
11,Norges Bank Account 2,"31,901,605",2.30,"31,706,807",2.40
12,Aberdeen Standard Asia Focus PLC,"28,123,572",2.03,"23,873,572",1.81
13,Mr Kandiah Balendra,"19,511,476",1.41,"19,511,476",1.48
14,Employees Trust Fund Board,"18,499,897",1.34,"18,709,833",1.42
15,Fidelity Fund - Pacific,"17,880,904",1.29,"17,880,904",1.35
16,Mrs C S De Fonseka,"17,472,745",1.26,"16,952,586",1.28
17,Mrs S A J De Fonseka,"15,204,230",1.10,"15,204,230",1.15
18,Edgbaston Asian Equity Trust,"15,142,109",1.09,"14,809,382",1.12
19,Chemanex PLC,"12,605,234",0.91,"11,417,835",0.87
20,Sri Lanka Insurance Corporation Limited - Life...,"12,270,665",0.89,-,-
21,Mr K N J Balendra,"10,907,628",0.79,"10,907,628",0.83
22,Schroder Asian Growth Fund,"10,328,047",0.75,"10,328,047",0.78

In [109]:
top_20_shareholders_table_2023

,0,1,2,3,4
0,Top Twenty Shareholders of the Company,NaN,NaN,NaN,NaN
1,NaN,31 March 2023,NaN,31 March 2022,NaN
2,NaN,Number of,%,Number of,%
3,NaN,shares,NaN,shares,NaN
4,Mr S E Captain,"134,044,705",9.68,"134,220,895",9.69
5,Melstacorp PLC,"128,917,111",9.31,"128,917,111",9.31
6,HWIC Asia Fund,"119,200,760",8.61,"119,200,760",8.61
7,Paints and General Industries Limited,"100,717,931",7.27,"140,437,428",10.14
8,Asian Development Bank,"65,042,006",4.70,"65,042,006",4.70
9,Citigroup Global Markets Limited Agency Tradin...,"61,904,939",4.47,"61,904,939",4.47
10,Schroder International Selection Fund,"44,418,290",3.21,"41,974,590",3.03
11,CIC Holdings PLC,"35,338,032",2.55,-,-
12,Aberdeen Standard Asia Focus PLC,"33,398,572",2.41,"28,123,572",2.03
13,Norges Bank Account 2,"31,901,605",2.30,"31,901,605",2.30
14,Sri Lanka Insurance Corporation Limited - Life...,"21,846,511",1.58,"12,270,665",0.89
15,Mr Kandiah Balendra,"19,511,476",1.41,"19,511,476",1.41
16,Employees Trust Fund Board,"18,499,897",1.34,"18,499,897",1.34
17,Mrs C S De Fonseka,"17,606,991",1.27,"17,472,745",1.26
18,Edgbaston Asian Equity Trust,"17,520,023",1.27,"15,142,109",1.09
19,Fidelity Fund - Pacific,"15,244,082",1.10,"17,880,904",1.29
20,Mrs S A J De Fonseka,"15,204,230",1.10,"15,204,230",1.10
21,Polypak Secco Limited,"14,937,924",1.08,-,-
22,Chemanex PLC,"13,105,475",0.95,"12,605,234",0.91
23,Sunsuper Superannuation Fund,"11,587,196",0.84,-,-

In [110]:
top_20_shareholders_table_2024

,0,1,2,3,4
0,Top Twenty Shareholders of the Company,NaN,NaN,NaN,NaN
1,NaN,31 March 2024,NaN,31 March 2023,NaN
2,NaN,Number of,%,Number of,%
3,NaN,shares,NaN,shares,NaN
4,HWIC Asia Fund,"291,105,699",19.42,"119,200,760",8.61
5,Melstacorp PLC,"128,917,111",8.60,"128,917,111",9.31
6,Mr S E Captain,"122,615,194",8.18,"134,044,705",9.68
7,Paints & General Industries Limited,"87,021,832",5.81,"100,717,931",7.27
8,CIC Holdings PLC,"85,365,926",5.70,"35,338,032",2.55
9,Asian Development Bank,"65,042,006",4.34,"65,042,006",4.70
10,Schroder International Selection Fund,"44,418,290",2.96,"44,418,290",3.21
11,Aberdeen Standard Asia Focus PLC,"35,038,572",2.34,"33,398,572",2.41
12,Norges Bank Account 2,"33,087,774",2.21,"31,901,605",2.30
13,Polypak Secco Limited,"31,587,170",2.11,"14,937,924",1.08
14,Mr Kandiah Balendra,"19,511,476",1.30,"19,511,476",1.41
15,Mrs C S De Fonseka,"17,606,991",1.17,"17,606,991",1.27
16,Emrevival Master Fund LP,"15,983,048",1.07,-,-
17,Mrs S A J De Fonseka,"15,254,730",1.02,"15,204,230",1.10
18,Hostplus Pooled Superannuation Trust,"15,152,416",1.01,"10,393,158",0.75
19,Chemanex PLC,"15,064,515",1.01,"13,105,475",0.95
20,Edgbaston Asian Equity Trust,"14,209,110",0.95,"17,520,023",1.27
21,Employees Trust Fund Board,"12,989,299",0.87,"18,499,897",1.34
22,Sunsuper Superannuation Fund,"12,964,947",0.87,"11,587,196",0.84
23,Mr K N J Balendra,"10,907,628",0.73,"10,907,628",0.79

In [111]:
import pandas as pd


df_shareholders = pd.DataFrame(columns=["Shareholder", "Shares", "Percentage", "Year"])


print(df_shareholders)

Empty DataFrame
Columns: [Shareholder, Shares, Percentage, Year]
Index: []

In [112]:
df_shareholders = pd.DataFrame(columns=["Shareholder", "Shares", "Percentage", "Year"])

df_2019_part = top_20_shareholders_table_2020.iloc[1:, [0, 3, 4]].copy()
df_2019_part.columns = ["Shareholder", "Shares", "Percentage"]

df_2019_part = df_2019_part[(df_2019_part['Shares'] != '-') & (df_2019_part['Percentage'] != '-')].dropna()

df_2019_part['Shares'] = df_2019_part['Shares'].astype(str).str.replace(",", "").astype(float)
df_2019_part['Percentage'] = df_2019_part['Percentage'].astype(str).str.replace(",", "").astype(float)
df_2019_part['Year'] = 2019

df_shareholders = pd.concat([df_shareholders, df_2019_part], ignore_index=True)

C:\Users\SHERONE\AppData\Local\Temp\ipykernel_29272\1457851307.py:12: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_shareholders = pd.concat([df_shareholders, df_2019_part], ignore_index=True)

In [113]:
df_2020_part = top_20_shareholders_table_2020.iloc[1:, [0, 1, 2]].copy()
df_2020_part.columns = ["Shareholder", "Shares", "Percentage"]
df_2020_part = df_2020_part[(df_2020_part['Shares'] != '-') & (df_2020_part['Percentage'] != '-')].dropna()
df_2020_part['Shares'] = df_2020_part['Shares'].astype(str).str.replace(",", "").astype(float)
df_2020_part['Percentage'] = df_2020_part['Percentage'].astype(str).str.replace(",", "").astype(float)
df_2020_part['Year'] = 2020

df_shareholders = pd.concat([df_shareholders, df_2020_part], ignore_index=True)

In [114]:
df_2021_part = top_20_shareholders_table_2021.iloc[4:, [0, 1, 2]].copy()
df_2021_part.columns = ["Shareholder", "Shares", "Percentage"]
df_2021_part = df_2021_part[(df_2021_part['Shares'] != '-') & (df_2021_part['Percentage'] != '-')].dropna()
df_2021_part['Shares'] = df_2021_part['Shares'].astype(str).str.replace(",", "").astype(float)
df_2021_part['Percentage'] = df_2021_part['Percentage'].astype(str).str.replace(",", "").astype(float)
df_2021_part['Year'] = 2021

df_shareholders = pd.concat([df_shareholders, df_2021_part], ignore_index=True)

In [115]:
df_2022_part = top_20_shareholders_table_2022.iloc[3:, [0, 1, 2]].copy()
df_2022_part.columns = ["Shareholder", "Shares", "Percentage"]
df_2022_part = df_2022_part[(df_2022_part['Shares'] != '-') & (df_2022_part['Percentage'] != '-')].dropna()
df_2022_part['Shares'] = df_2022_part['Shares'].astype(str).str.replace(",", "").astype(float)
df_2022_part['Percentage'] = df_2022_part['Percentage'].astype(str).str.replace(",", "").astype(float)
df_2022_part['Year'] = 2022

df_shareholders = pd.concat([df_shareholders, df_2022_part], ignore_index=True)

In [116]:
df_2023_part = top_20_shareholders_table_2023.iloc[4:, [0, 1, 2]].copy()
df_2023_part.columns = ["Shareholder", "Shares", "Percentage"]
df_2023_part = df_2023_part[(df_2023_part['Shares'] != '-') & (df_2023_part['Percentage'] != '-')].dropna()
df_2023_part['Shares'] = df_2023_part['Shares'].astype(str).str.replace(",", "").astype(float)
df_2023_part['Percentage'] = df_2023_part['Percentage'].astype(str).str.replace(",", "").astype(float)
df_2023_part['Year'] = 2023

df_shareholders = pd.concat([df_shareholders, df_2023_part], ignore_index=True)

In [117]:
df_2024_part = top_20_shareholders_table_2023.iloc[4:, [0, 1, 2]].copy()
df_2024_part.columns = ["Shareholder", "Shares", "Percentage"]
df_2024_part = df_2024_part[(df_2024_part['Shares'] != '-') & (df_2024_part['Percentage'] != '-')].dropna()
df_2024_part['Shares'] = df_2024_part['Shares'].astype(str).str.replace(",", "").astype(float)
df_2024_part['Percentage'] = df_2024_part['Percentage'].astype(str).str.replace(",", "").astype(float)
df_2024_part['Year'] = 2024

df_shareholders = pd.concat([df_shareholders, df_2024_part], ignore_index=True)

In [118]:
df_shareholders

                               Shareholder       Shares  Percentage  Year
0                           Mr S E Captain  152991389.0       11.61  2019
1                           Melstacorp PLC  128572406.0        9.75  2019
2      Paints & General Industries Limited   86673704.0        6.58  2019
3    Schroder International Selection Fund   42417426.0        3.22  2019
4                           HWIC Asia Fund   36000982.0        2.73  2019
..                                     ...          ...         ...   ...
114                Fidelity Fund - Pacific   15244082.0        1.10  2024
115                   Mrs S A J De Fonseka   15204230.0        1.10  2024
116                  Polypak Secco Limited   14937924.0        1.08  2024
117                           Chemanex PLC   13105475.0        0.95  2024
118           Sunsuper Superannuation Fund   11587196.0        0.84  2024

[119 rows x 4 columns]

In [119]:
df_shareholders.to_json("shareholders.json", orient="records", indent=2)

In [ ]:
import os
import camelot
import pandas as pd

def extract_data_from_pdf(pdf_path, pages_to_extract, output_folder, start_index=1):
    os.makedirs(output_folder, exist_ok=True)

    extracted_data = {}

    for label, page in pages_to_extract.items():
        print(f"Extracting '{label}' from page {page} of '{pdf_path}'")
        tables = camelot.read_pdf(pdf_path, pages=str(page), flavor='stream')

        if tables:
            extracted_data[label] = [t.df for t in tables]
        else:
            print(f"No tables found on page {page}.")

    for label, dfs in extracted_data.items():
        for idx, df in enumerate(dfs, start=start_index):
            filename = f"{label}_table_{idx}.csv"
            csv_path = os.path.join(output_folder, filename)
            df.to_csv(csv_path, index=False)
            print(f"Saved: {csv_path}")

pdf_files = [
    {
        "pdf_path": "2021.pdf",
        "pages_to_extract": {
            "Industry wise quaterly perfomance": 22,
            
        },
        "output_folder": "quaterly/2021",
        "start_index": 2021
    },
    {
        "pdf_path": "2022.pdf",
        "pages_to_extract": {
            "Industry wise quaterly perfomance": 23,
            
        },
        "output_folder": "quaterly/2022",
        "start_index": 2022
    },
    {
        "pdf_path": "2023.pdf",
        "pages_to_extract": {
            "Industry wise quaterly perfomance": 27,
            
        },
        "output_folder": "quaterly/2023",
        "start_index": 2023
    },
    {
        "pdf_path": "2024.pdf",
        "pages_to_extract": {
            "Industry wise quaterly perfomance": 26,
            
        },
        "output_folder": "quaterly/2024",
        "start_index": 2024
    },
   
    
   
]

for pdf_file in pdf_files:
    extract_data_from_pdf(
        pdf_path=pdf_file["pdf_path"],
        pages_to_extract=pdf_file["pages_to_extract"],
        output_folder=pdf_file["output_folder"],
        start_index=pdf_file.get("start_index", 1)
    )

Extracting 'Industry wise quaterly perfomance' from page 22 of '2021.pdf'
Saved: quaterly/2021\Industry wise quaterly perfomance_table_2021.csv
Saved: quaterly/2021\Industry wise quaterly perfomance_table_2022.csv
Saved: quaterly/2021\Industry wise quaterly perfomance_table_2023.csv
Saved: quaterly/2021\Industry wise quaterly perfomance_table_2024.csv
Extracting 'Industry wise quaterly perfomance' from page 23 of '2022.pdf'
Saved: quaterly/2022\Industry wise quaterly perfomance_table_2022.csv
Extracting 'Industry wise quaterly perfomance' from page 27 of '2023.pdf'
Saved: quaterly/2023\Industry wise quaterly perfomance_table_2023.csv
Saved: quaterly/2023\Industry wise quaterly perfomance_table_2024.csv
Extracting 'Industry wise quaterly perfomance' from page 26 of '2024.pdf'
Saved: quaterly/2024\Industry wise quaterly perfomance_table_2024.csv

In [ ]:

folder_path = "quaterly"

combined_data = []

for file in sorted(os.listdir(folder_path)):
    if file.endswith(".csv"):
        year_label = file.replace(".csv", "").split("_")[-1]  # e.g., 2020_21
        df = pd.read_csv(os.path.join(folder_path, file), index_col=0)

        df = df[df.index.notna()]
        df = df.dropna(how='all')

        mid = df.shape[1] // 2
        quarters = ['Q1', 'Q2', 'Q3', 'Q4']
        df.columns = quarters * 2
        ebitda_df = df[quarters].copy()
        yoy_df = df[quarters].copy()

        for sector in df.index:
            sector_name = str(sector).strip()
            for q in quarters:
                combined_data.append({
                    "Year": year_label,
                    "Sector": sector_name,
                    "Quarter": q,
                    "EBITDA": ebitda_df.loc[sector][q],
                    "YoY %": yoy_df.loc[sector][q]
                })
final_df = pd.DataFrame(combined_data)
final_df.to_json("combined_quarterly_ebitda.json", orient="records", indent=2)